services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    # command: ["tail", "-f", "/dev/null"]
    environment:
      - ENV=development
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: sync+restart
          path: ./server
          ignore: requests/
          target: /app
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s