services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    # command: ["tail", "-f", "/dev/null"]
    environment:
      - ENV=development
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: sync+restart
          path: ./server
          ignore: requests/
          target: /app
    depends_on:
      postgres:
        condition: service_healthy
