templ:
	go tool templ generate

templ-dev:
	go tool templ generate -watch

dev:
	set -a; source .env; set +a; /Users/mpcarolin/go/bin/air .

dlv:
	set -a; source .env; set +a; /Users/mpcarolin/go/bin/dlv debug .
