// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article><header><hgroup><h1>About</h1><p>Cinematch is an app that helps you find what to watch next.</p></hgroup></header><p>For years, my partner and I struggled to decide a movie to watch on movie night. We'd flip through streaming services and movie lists, only to end up with dozens of choices, dozens more reviews of varying quality, and no closer to a decision.</p><p>One day, we went to a movie theater. As we watched the previews, I noticed how easy it was for my wife and I to come to agree on movies we wanted to watch together in the future. There were no distractions. No reviews to read, no ratings or comments to bias you in one direction or another. We were able to make a choice based on a <b>curated</b> set of <b>a handful of</b> trailers in front of us, simple as that.</p><p>I wondered why we couldn't have a similar experience at home.</p><p>So, Cinematch was born.</p><p>The best part? It's free. <small>(...though donations are appreciated 🙂)</small></p><footer><p>Cinematch uses the <a href=\"https://www.themoviedb.org/\">TMDB</a> API to get the best recommendations for any movie you want to watch.</p></footer></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
