// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article><header><hgroup><h1>About</h1><p>ReelGroove: Because endless scrolling through streaming services isn't a hobby, it's a cry for help.</p></hgroup></header><p>Picture this: You and your partner, 45 minutes deep into \"What should we watch?\"  You've scrolled through every streaming service, read 37 conflicting reviews,  and somehow you're now watching cat videos on YouTube. Sound familiar?</p><p>One day it hit me - movie theaters have it right with previews. No endless choices, no review paralysis,  just a few trailers and boom - you got movies you're both excited about.</p><p>Enter ReelGroove: Your personal movie matchmaker. We cut through the noise,  show you the good stuff, and get you watching faster than you can say \"Netflix and chill.\"</p><p>Best part? It's free. <small>(But if you want to buy us a coffee, we won't say no 😉)</small></p><footer><p>Powered by the <a href=\"https://www.themoviedb.org/\">TMDB</a> API</p></footer></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
